aka3 = list(
    Histology   = c(
        Pancreatic_NEN = "BLACK",
        Colorectal_NEN = "Orange",
        Small_intestinal_NEN = "Yellow",
        Gastric_NEN = "purple",
        Liver = "Darkgreen",
        CUP = "pink"),
    Deco_type = c(alpha = "Blue",beta = "Yellow",gamma = "Orange",delta = "Purple", e13.5 = "Brown", hsc = "white"),
    ABC_GCB = c(ABC= "darkgreen", GCB = "darkred", Unclassified = "white","PMBL"= "gray"),
    #Left_Right = c("left"= "green", "right" = "white"),
    Left_Right = c("high" = "darkred", "medium" = "yellow" ,"low" ="white"),
    Complex = c(clean = "white", complex = "orange", na = "gray"),
    Cluster = c("0" = "gray", "1" = "white", "2" = "green", "3" = "blue", "4" = "brown", "5" = "black"),
    Cluster_SUV = c("SUV_high" = "darkred", "SUV_low" = "white"),
    Drug_Treatment = c("RES"="black","NR"="darkgreen","RP" = "orange") ,
    #Drug_Treatment = c("NR"="White","RP" = "orange") ,
    SUVARNESS = c("high" = "darkred", "medium" = "yellow" ,"low" ="white"),
    "TIS up" = c("high" = "darkred", "medium" = "yellow" ,"low" ="white"),
    "TIS down" = c("high" = "white", "medium" = "yellow" ,"low" ="darkred"),
    CARDness = c("high" = "darkred", "medium" = "yellow" ,"low" ="white"),
    PFS_vis = c("Progression" = "black", "No_progression" = "white"),
    Progression = c("Progression" = "black", "No Progression" = "white"),
    ML_core = c("high" = "black", "low" = "white"),
    TANG_SENESCENCE_TP53_TARGETS_DN = c("high" = "black", "low" = "white"),
    Left_Right_Hema_combined = c("high" = "black", "low" = "white"),
    "TIS.down" = c("high" = "black", "low" = "white"),
    "E2F.target.genes" = c("high" = "black", "low" = "white"),
    TANG_SENESCENCE_TP53_TARGETS_DN = c("NR" = "black", "NP" = "white"),
    Grading = c( G0 = "white",G1 = "Green",G2 = "Yellow", G3 = "Red"),
    NEC_NET = c(Healthy = "white",NEC= "red", NET = "blue", Ambiguous = "purple"),
    NEC_NET_PCA = c(NEC= "red", NET = "blue", Unknown = "white"),
    NEC_NET_Color = c(NEC= "red", NET = "blue", Ambiguous = "purple"),
    Study = c(Riemer = "gray", Scarpa = "darkgreen"),
    #Predicted = c("Never Relapsed" = "green", "Relapse Prone" = "yellow", "Resistant" = "red"),
    Predicted = c("Never.Relapsed" = "green", "RPR" = "red"),
    "Left_Right_ML_core_50" = c("left" = "blue", "right" = "red")
)
