aka3 = list(
    Histology   = c(
        Pancreatic_NEN = "BLACK",
        Colorectal_NEN = "Orange",
        Small_intestinal_NEN = "Yellow",
        Gastric_NEN = "purple",
        Liver = "Darkgreen",
        CUP = "pink"),
    Deco_type = c(alpha = "Blue",beta = "Yellow",gamma = "Orange",delta = "Purple", e13.5 = "Brown", hsc = "white"),
    ABC_GCB = c(ABC= "darkgreen", GCB = "darkred", Unclassified = "white","PMBL"= "gray"),
    Left_Right = c("left"= "blue", "right" = "red"),
    #Left_Right = c("high" = "darkred", "medium" = "yellow" ,"low" ="white"),
    Complex = c(clean = "white", complex = "orange", na = "gray"),
    Cluster = c("0" = "gray", "1" = "white", "2" = "green", "3" = "blue", "4" = "brown", "5" = "black"),
    Cluster_SUV = c("SUV_high" = "darkred", "SUV_low" = "white"),
    Drug_Treatment = c("RES"="black","NR"="darkgreen","RP" = "orange") ,
    #Drug_Treatment = c("NR"="White","RP" = "orange") ,
    SUVARNESS = c("high" = "darkred", "medium" = "yellow" ,"low" ="white"),
    "TIS up" = c("high" = "darkred", "medium" = "yellow" ,"low" ="white"),
    "TIS down" = c("high" = "white", "medium" = "yellow" ,"low" ="darkred"),
    CARDness = c("high" = "darkred", "medium" = "yellow" ,"low" ="white"),
    PFS_vis = c("Progression" = "black", "No_progression" = "white"),
    Progression = c("Progression" = "black", "No Progression" = "white"),
    ML_core = c("High" = "black", "Low" = "white"),
    TANG_SENESCENCE_TP53_TARGETS_DN = c("high" = "black", "low" = "white"),
    Left_Right_Hema_combined = c("high" = "black", "low" = "white"),
    "TIS.down" = c("High" = "black", "Medium_Low" = "white"),
    "TIS.up" = c("High" = "black", "Medium_Low" = "white"),
    "E2F.target.genes" = c("high" = "black", "low" = "white"),
    TANG_SENESCENCE_TP53_TARGETS_DN = c("NR" = "black", "NP" = "white"),
    Study = c("Charite" = "gray", Scarpa = "darkgreen"),
    Predicted = c("Never.Relapsed" = "green", "RPR" = "red"),
    "Left_Right_ML_core_50" = c("left" = "blue", "right" = "red"),
    bgal_binary = c("High" = "black", "Low" = "white","Unknown"="gray"),
    ADR_binary = c("high" = "black", "low" = "white"),
    ADROHT_binary = c("high" = "black", "low" = "white"),
    PS_binary = c("high" = "black", "low" = "white","unknown" = "gray"),
    B_cell_state = c(S01 = "#76a1ca", S02 = "#562665", S03 = "#08f9cb", S04 = "#a91b73", S05 = "#79db30", "Unknown"= "Gray"),
    Lymphoma_Ecotype = c("LE3" = "#3c3dad", "LE6" = "#b01511", "LE7" = "#ee9f53", "Unknown" = "gray"),
    Cell_state = c("S01" = "red", "S02" = "blue","S03" = "#b01511","S04" = "#ee9f53", "S05" = "#9D33FF"),
    TIS_cluster = c("TIS down" = "red","TIS mixed" = "yellow","TIS up" = "blue"),
    Response = c("RP-like" = "blue", "NR-like" = "red")
)
